# Generated by Django 4.1.5 on 2023-01-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('n', models.IntegerField()),
                ('result', models.IntegerField()),
                ('elapsed_time', models.CharField(max_length=50)),
            ],
        ),
    ]
